server:
  port: 10303

spring:
  main:
    allow-bean-definition-overriding: true
  cache:
    cache-names: local-cache
    type: caffeine
    caffeine.spec: initialCapacity=500,maximumSize=100000,expireAfterWrite=1m
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: dbcp1
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/opt/data-layer/soul-admin/data:public;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: nouser
    password: nopassword
    # schema[0]: classpath:/auth.sql
    #    initialization-mode: ALWAYS
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database:
      platform: org.hibernate.dialect.H2Dialect
  redis:
    host: 127.0.0.1
    port: 6379

thread-pool-props:
  corePoolSize: 5
  maxPoolSize: 100
  keepAliveSeconds: 100
  queueCapacity: 1000

# 配置健康检查
management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true
    threaddump:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,metrics,threaddump,prometheus
        exclude: shutdown
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    redis:
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl